### ISSUE TITLE
Hover Animation On Initails Logo

### ISSUE THREAD

**Issue by amcnulty** [amcnulty/Aaron-Michael#4]
Add a hover effect to the initials logo on the landing page. Use the following code as an example
### HTML
```html
<div id="wrapper">
  <div id="thumbnail" href="#">
    Test Me
  </div>
</div>
```
### CSS
```css
#wrapper {
  width: 100%;
  padding-top: 100px;
  perspective: 300px;
}

#thumbnail {
	display: block;
  margin: 0 auto;
	width: 150px;
	height: 150px;
  line-height: 150px;
  background-color: blue;
  color: white;
  text-align: center;
  transition: all .2s ease-out;
}
```
### JS
```javascript
var thumbnail = document.getElementById("thumbnail");

thumbnail.addEventListener("mousemove", function(e){
  var x = e.offsetX;
  var y = e.offsetY;
  if (x > 74) {
    x = Math.floor((x - 74) / 3);
  }
  else x = -Math.floor((74 - x) / 3);
  
  if (y > 74) {
    y = -Math.floor((y - 74) / 3);
  }
  else y = Math.floor((74 - y) / 3);
  thumbnail.innerHTML = `X: ${x} Y: ${y}`;
  thumbnail.style.transform = `rotateY(${x}deg) rotateX(${y}deg)`;
}, false);

thumbnail.addEventListener("mouseout", function(e) {
  thumbnail.style.transform = `rotateY(0deg) rotateX(0deg)`
}, false);
```
